#!/bin/bash
#SBATCH --partition=short        
#SBATCH --job-name=lab4  
#SBATCH --output=lab4.out        
#SBATCH --error=lab4.err         
#SBATCH --time=0-01:00:00        
#SBATCH --nodes=1                
#SBATCH --ntasks-per-node=1      
#SBATCH --cpus-per-task=8                
#SBATCH --mem-per-cpu=16GB       
#SBATCH --account=edld654

R CMD BATCH --no-save --no-restore lab_4_knn_model.R